{% set name = "Deprecated" %}
{% set version = "1.2.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 6ec624c168290715d56c6af7c1c1066ea5c732bd56427b1651db75ede923aa38

build:
  number: 0
  noarch: python
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wrapt <2,>=1.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - deprecated

about:
  home: https://github.com/tantale/deprecated
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: https://github.com/tantale/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dbast
