{% set name = "Deprecated" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|lower }}-{{ version }}.tar.gz
  sha256: 16850204d3a1e6bb0acd06bff48d96e8b0a0d25d1c52f71705405a0f4894192d

build:
  number: 0
  noarch: python
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - wrapt <3,>=1.10

test:
  requires:
    - python {{ python_min }}
  imports:
    - deprecated

about:
  home: https://github.com/tantale/deprecated
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: https://github.com/tantale/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
    - dbast
