{% set name = "Deprecated" %}
{% set version = "1.2.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 471ec32b2755172046e28102cd46c481f21c6036a0ec027521eba8521aa4ef35

build:
  number: 0
  noarch: python
  script: python -m pip install --ignore-installed --no-deps .

requirements:
  host:
    - python
    - pip
    - wrapt <2,>=1
  run:
    - python
    - wrapt <2,>=1

test:
  imports:
    - deprecated

about:
  home: https://github.com/tantale/deprecated
  license: MIT
  license_file: LICENSE.rst
  license_family: MIT
  # https://github.com/tantale/deprecated/pull/1
  # license_file: ''
  summary: Python @deprecated decorator to deprecate old python classes, functions or methods.
  dev_url: https://github.com/tantale/deprecated

extra:
  recipe-maintainers:
    - mariusvniekerk
